# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  deliverToClientRepositry:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git remote add test3 https://github.com/Yuto-Nakano/circleci-test-3.git
      - run: git push test3 master
workflows:
  build-and-deploy:
    jobs:
      - deliverToClientRepositry:
          filters:
            branches:
              only: master
